# Generated by Django 5.1.1 on 2024-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.CharField(max_length=1000)),
                ('bot_response', models.CharField(max_length=1000)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
