# Generated by Django 5.1.1 on 2024-09-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_message',
            new_name='user_text',
        ),
    ]
