# Generated by Django 5.1.1 on 2024-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_user_message_chat_user_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
